


services:
  web:
   build: flask-producer
   command: python -u run.py
   ports:
     - "5000:5000"
   volumes:
     - ./flask-producer:/app
   depends_on:
    - rabbit
   networks:
     - frontend
     - backend
  worker1:
    build: mongo-consumer
    command: python -u worker.py
    ports:
      - "5001:5001"
    volumes:
      - ./mongo-consumer
    depends_on:
      - mongodb
      - rabbit
      - redis
    networks:
      - frontend
      - backend
  worker2:
    build: mongo-consumer
    command: python -u worker.py
    ports:
      - "5002:5002"
    volumes:
      - ./mongo-consumer
    depends_on:
      - mongodb
      - rabbit
      - redis
    networks:
      - frontend
      - backend
  worker3:
    build: mongo-consumer
    command: python -u worker.py
    ports:
      - "5003:5003"
    volumes:
      - ./mongo-consumer
    depends_on:
      - mongodb
      - rabbit
      - redis
    networks:
      - frontend
      - backend
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - frontend
  rabbit:
      hostname: rabbit
      image: rabbitmq:latest
      environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=pass
      ports:
        - "15672:15672"
        - "5672:5672"
      networks:
        - backend
  redis:
      image: redis:latest
      ports:
        - "6379:6379"
      networks:
        - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

